"""User management and password hashing.

The user list is an INI-style file with a ``[default]`` section, one
``username: hash`` pair per line (same format as before v2). Two hash
schemes are understood:

- ``pbkdf2_sha256$<iterations>$<salt-b64>$<digest-b64>`` — modern scheme,
  generated by :func:`hash_password` / ``ftp2ocr mkpasswd``.
- anything else — treated as a classic crypt(3) hash and verified with
  the optional ``legacycrypt`` package. Old user files keep working.
"""

from __future__ import annotations

import base64
import configparser
import hashlib
import hmac
import logging
import os
from dataclasses import dataclass
from pathlib import Path

from pyftpdlib.authorizers import AuthenticationFailed, DummyAuthorizer

from ftp2ocr.paths import PathFactory

_log = logging.getLogger(__name__)

PBKDF2_PREFIX = "pbkdf2_sha256"
DEFAULT_ITERATIONS = 600_000
_SALT_BYTES = 16


@dataclass(frozen=True)
class UserEntry:
    username: str
    passwd: str


def hash_password(password: str, *, iterations: int = DEFAULT_ITERATIONS) -> str:
    """Hash *password* with PBKDF2-HMAC-SHA256 into the stored format."""
    salt = os.urandom(_SALT_BYTES)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, iterations)
    return (
        f"{PBKDF2_PREFIX}${iterations}"
        f"${base64.urlsafe_b64encode(salt).decode('ascii')}"
        f"${base64.urlsafe_b64encode(digest).decode('ascii')}"
    )


def _verify_pbkdf2(password: str, stored: str) -> bool:
    try:
        _prefix, iterations_raw, salt_b64, digest_b64 = stored.split("$")
        iterations = int(iterations_raw)
        salt = base64.urlsafe_b64decode(salt_b64)
        digest = base64.urlsafe_b64decode(digest_b64)
    except (ValueError, TypeError):
        _log.error("Malformed pbkdf2 password hash")
        return False
    if iterations <= 0:
        _log.error("Invalid iteration count in pbkdf2 password hash")
        return False
    candidate = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, iterations)
    return hmac.compare_digest(candidate, digest)


def _verify_legacy(password: str, stored: str) -> bool:
    try:
        import legacycrypt as crypt
    except ImportError:
        _log.error(
            "User entry uses a legacy crypt hash but 'legacycrypt' is not installed; "
            "regenerate the password hash with 'ftp2ocr mkpasswd'"
        )
        return False
    try:
        hashed = crypt.crypt(password, stored)
    except ValueError:
        _log.error("Unsupported legacy crypt scheme in stored hash")
        return False
    if not hashed:
        return False
    return hmac.compare_digest(hashed, stored)


def verify_password(password: str, stored: str) -> bool:
    """Verify *password* against a stored hash in either supported scheme."""
    if stored.startswith(f"{PBKDF2_PREFIX}$"):
        return _verify_pbkdf2(password, stored)
    return _verify_legacy(password, stored)


def read_user_list(list_file: Path | str) -> list[UserEntry]:
    """Parse the user list file (``[default]`` section, ``user: hash`` lines)."""
    cfg = configparser.ConfigParser()
    cfg.read(list_file)

    dflt = cfg["default"]
    return [UserEntry(username=user, passwd=dflt[user]) for user in dflt]


class UserManager(DummyAuthorizer):
    """pyftpdlib authorizer that creates the per-user directory tree."""

    def __init__(self, path_factory: PathFactory, user_list: list[UserEntry]):
        super().__init__()

        self._path_factory = path_factory
        self._user_list = user_list

        self._init_users()

    def _init_users(self) -> None:
        for user in self._user_list:
            self._path_factory.ensure_user_dirs(user.username)

            self.add_user(
                user.username,
                password=user.passwd,
                homedir=str(self._path_factory.home(user.username)),
                perm="el",
            )
            for path in (
                self._path_factory.new_raw(user.username),
                self._path_factory.new_duplex(user.username),
                self._path_factory.new_simplex(user.username),
                self._path_factory.observed(user.username),
            ):
                self.override_perm(user.username, str(path), "elrawMT", recursive=True)

    def users(self) -> list[UserEntry]:
        return list(self._user_list)

    def validate_authentication(self, username: str, password: str, handler) -> None:
        try:
            stored = self.user_table[username]["pwd"]
        except KeyError:
            raise AuthenticationFailed("No such user") from None

        if not isinstance(stored, str) or not verify_password(password, stored):
            raise AuthenticationFailed("Wrong password")
